FROM python:3.9

WORKDIR /app

COPY flask_api/requirements.txt requirements.txt

# Upgrade pip and install requirements
RUN pip install --upgrade pip && \
    pip install -r requirements.txt

COPY flask_api/ .

CMD ["python", "app.py"]
